config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from ibis_core.activity.views import ActivitiesListView
from ibis_core.common.views import SuggestView, GlobalSearchView, ThemeChidlrensView, ThemeListViewAPI, \
    UserManagementAPI
from ibis_core.dashboard.views import DashboardView
from ibis_core.searches.views import TestGoogleCSEQuery
from ibis_core.themes.views import ThemeListView

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^search/', view=GlobalSearchView.as_view(), name='global_search'),

    # User management
    url(r'^users/', include('ibis_core.users.urls', namespace='users')),

    # Themes management
    url(r'^themes/', include('ibis_core.themes.urls', namespace='themes')),

    # Groups management
    url(r'^groups/', include('ibis_core.groups.urls', namespace='groups')),

    # Issues management
    url(r'^issues/', include('ibis_core.issues.urls', namespace='issues')),

    # Searches management
    url(r'^searches/', include('ibis_core.searches.urls', namespace='searches')),

    # Articles management
    url(r'^articles/', include('ibis_core.articles.urls', namespace='articles')),

    url(r'^feedback/', include('ibis_core.feedback.urls', namespace='feedbacks')),

    # Daily Digest management
    url(r'^digest/', include('ibis_core.digest.urls', namespace='digest')),

    # User accounts management
    url(r'^accounts/', include('allauth.urls')),

    url(r'^activities/', view=ActivitiesListView.as_view(), name='activities_list'),



    url(r'^api/v1/testquery',
        view=TestGoogleCSEQuery.as_view(),
        name='api_testquery'),

    url(r'^api/v1/suggest',
        view=SuggestView.as_view(),
        name='api_suggest'),


    url(r'^api/v1/theme/(?P<slug>[\w-]+)$',
        view=ThemeChidlrensView.as_view(),
        name='api_um_theme'),

    url(r'^api/v1/themes$',
        view=ThemeListViewAPI.as_view(),
        name='api_um_themes'),

    url(r'^api/v1/umdata$',
        view=UserManagementAPI.as_view(),
        name='api_um_data'),





    # Your stuff: custom urls includes go here

    # Summernote WYSIWYG editor URL's
    url(r'^summernote/', include('django_summernote.urls')),

    # Included Django Comments
    url(r'^comments/', include('django_comments_xtd.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

ibis_core/digest/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the DigestListView
    url(
        regex=r'^$',
        view=views.DigestListView.as_view(),
        name='list'
    ),

    # URL pattern for the DigestDetailView
    url(
        regex=r'^(?P<pk>[\w-]+)$',
        view=views.DigestDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the DigestUpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.DigestUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^(?P<pk>[\w-]+)/~approvestate$',
        view=views.DigestApproveStateView.as_view(),
        name='approvestate'
    ),

    # url(
    #     regex=r'^(?P<digest_pk>[0-9a-z-]+)/~remove_article/(?P<article_pk>[0-9a-z-]+)$',
    #     view=views.DigestRemoveArticleView.as_view(),
    #     name='remove-article-from-digest'
    # )
]

ibis_core/groups/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from ibis_core.groups.views import GroupAddExistingIssueView
from . import views
from ibis_core.issues.views import IssueCreateView

urlpatterns = [
    # URL pattern for the GroupListView
    url(
        regex=r'^$',
        view=views.GroupListView.as_view(),
        name='list'
    ),

    # URL pattern for the CreateGroup
    url(
        regex=r'^~new/$',
        view=views.GroupCreateView.as_view(),
        name='create'
    ),

    # URL pattern for the GroupDetailView
    url(
        regex=r'^(?P<slug>[\w-]+)$',
        view=views.GroupDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the GroupUpdateView
    url(
        regex=r'^(?P<slug>[\w-]+)/~update$',
        view=views.GroupUpdateView.as_view(),
        name='update'
    ),

    # Urls for group issues
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_issue/$',
        view=IssueCreateView.as_view(),
        name='add_group_issue'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~add_existing_issue/$',
        view=GroupAddExistingIssueView.as_view(),
        name='add_group_existing_issue'
    ),

    # Urls for user management inside group
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_members/$',
        view=views.GroupUsersAddView.as_view(),
        name='add_group_member_list'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~to_moderator/(?P<pk>[0-9]+)$',
        view=views.GroupUserToModerator.as_view(),
        name='to_moderator'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~remove_member/(?P<pk>[0-9]+)$',
        view=views.GroupUsersDeleteView.as_view(),
        name='remove_group_member'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~follow/$',
        view=views.GroupFollowView.as_view(),
        name='group_follow'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~unfollow/$',
        view=views.GroupUnfollowView.as_view(),
        name='group_unfollow'
    ),

]

ibis_core/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    url(
        regex=r'^profile$',
        view=views.UserProfileView.as_view(),
        name='profile'
    ),

    # URL pattern for the UserCreateView
    url(
        regex=r'^~new/$',
        view=views.UserCreateView.as_view(),
        name='create'
    ),


    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.UserEditView.as_view(),
        name='update_user'
    ),

]

ibis_core/activity/models.py
import uuid

import redis
from django.contrib.contenttypes import fields
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.conf import settings
from django.template.loader import render_to_string

from ibis_core.common.models import AbstractBaseModel

EVENT_TYPE_CREATE = 'create'

# redis_connection = redis.StrictRedis.from_url(settings.REDIS_ACTIVITY_URL)
redis_connection = redis.StrictRedis(host='0.0.0.0', port='6380', db=1, charset="utf-8", decode_responses=True)


class EventManager(models.Manager):
    def get_user_activity_stream(self, user, offset=0, limit=11):
        events_ids = redis_connection.zrange('activity:stream:user:%d' % user.id, offset, limit, desc=True)
        if len(events_ids):
            return self.filter(id__in=events_ids).order_by('-created')
        return []


class Event(AbstractBaseModel):
    objects = EventManager()

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='activities'
    )

    target_content_type = models.ForeignKey(ContentType, related_name='event_target')
    target_id = models.UUIDField(default=uuid.uuid4, editable=False)
    target = fields.GenericForeignKey('target_content_type', 'target_id')

    event_type = models.CharField(max_length=200, default=EVENT_TYPE_CREATE)

    def __str__(self):
        template_name = "activities/%s_activity.txt" % self.event_type
        try:
            repr = render_to_string(template_name=template_name, context=dict(
                actor=self.actor,
                target_model=self.target._meta.model_name,
                target_url=self.target.get_absolute_url,
                target_name=self.target.name
            ))
        except AttributeError:
            repr = self.actor

        return repr


class EventMixin(object):
    class Meta:
        abstract = True

    def create_event(self, actor, event_type=EVENT_TYPE_CREATE):
        target_content_type = ContentType.objects.get_for_model(self)
        Event.objects.create(
            actor=actor,
            target_id=self.id,
            target_content_type_id=target_content_type.id,
            event_type=event_type
        )

    def get_followers(self):
        raise NotImplementedError

ibis_core/comments/models.py
from django.db import models
from django_comments.signals import comment_will_be_posted

from django_comments_xtd.models import XtdComment


class IssueComment(XtdComment):
    title = models.CharField(max_length=256)

    @classmethod
    def tree_from_queryset(cls, queryset, with_participants=False):
        """Converts a XtdComment queryset into a list of nested dictionaries.
        The queryset has to be ordered by thread_id, order.
        Each dictionary contains two attributes::
            {
                'comment': the comment object itself,
                'children': [list of child comment dictionaries]
            }
        """

        def get_participants(comment):
            return {'likedit': comment.users_who_liked_it(),
                    'dislikedit': comment.users_who_disliked_it()}

        def add_children(children, obj):
            for item in children:
                if item['comment'].pk == obj.parent_id:
                    child_dict = {'comment': obj, 'children': []}
                    if with_participants:
                        child_dict.update(get_participants(obj))
                    item['children'].append(child_dict)
                    return True
                elif item['children']:
                    if add_children(item['children'], obj):
                        return True
            return False

        dic_list = []
        cur_dict = None
        for obj in queryset.order_by('thread_id', 'order'):
            # A new comment at the same level as thread_dict.
            if cur_dict and obj.level == cur_dict['comment'].level:
                dic_list.append(cur_dict)
                cur_dict = None
            if not cur_dict:
                cur_dict = {'comment': obj, 'children': []}
                if with_participants:
                    cur_dict.update(get_participants(obj))
                continue
            if obj.parent_id == cur_dict['comment'].pk:
                child_dict = {'comment': obj, 'children': []}
                if with_participants:
                    child_dict.update(get_participants(obj))
                cur_dict['children'].append(child_dict)
            else:
                add_children(cur_dict['children'], obj)
        if cur_dict:
            dic_list.append(cur_dict)
        return dic_list


def comment_will_be_posted_callback(**kwargs):
    request = kwargs['request']
    kwargs['comment'].ip_address = request.META.get('HTTP_REMOTE_ADDR', '127.0.0.1')

comment_will_be_posted.connect(comment_will_be_posted_callback)

ibis_core/dashboard/models.py
from django.db import models

# Create your models here.

ibis_core/feedback/models.py
from django.db import models

from ibis_core.common.models import AbstractBaseModel


class Feedback(AbstractBaseModel):

    email = models.EmailField(blank=True)
    body = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.email

ibis_core/articles/forms.py
import json

from django import forms
from django_summernote.widgets import SummernoteWidget

from ibis_core.articles.models import Article


class ArticleEditForm(forms.ModelForm):
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs={
                               'class': 'form-control'}))

    class Meta:
        model = Article
        fields = ['body', 'translated_body', 'status', 'channel']
        widgets = {
            'body': SummernoteWidget(),
            'translated_body': SummernoteWidget(),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'channel': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_tags(self):
        data = self.data.get('tags')
        cleaned_tags = list(set(data.split(',')))
        return cleaned_tags


class StatusChangeAjaxForm(forms.ModelForm):
    # status = forms.CharField(required=True, widget=forms.Select(attrs={
    #     'class': 'form-control'
    # }))
    class Meta:
        model = Article
        fields = ('status',)
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

ibis_core/comments/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment


class IssueCommentForm(XtdCommentForm):
    title = forms.CharField(
        max_length=256,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('title'),
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super(IssueCommentForm, self).__init__(*args, **kwargs)
        for field_name, field_obj in self.fields.items():
            field_obj.widget.attrs.update({'class': 'form-control'})

    def get_comment_create_data(self):
        data = super(IssueCommentForm, self).get_comment_create_data()
        data.update({'title': self.cleaned_data['title']})
        return data

ibis_core/digest/forms.py
from django import forms

from ibis_core.digest.models import DailyDigest


class DigestArticleRemoveForm(forms.Form):
    article = forms.CharField(widget=forms.HiddenInput())


class DigestApproveStateForm(forms.Form):
    state = forms.CharField(widget=forms.HiddenInput())

ibis_core/issues/forms.py
from django import forms

from ibis_core.issues.models import Issue


class CreateIssueForm(forms.ModelForm):
    """
    Form for creating an Issue and bind chosen articles to it.
    """
    class Meta:
        model = Issue
        fields = ('name', 'access',)


class PaginateArticlesForm(forms.Form):
    def __init__(self, paginate_choices, *args, **kwargs):
        super(PaginateArticlesForm, self).__init__(*args, **kwargs)
        self.fields['paginate_by'].choices = paginate_choices

    paginate_by = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={'class': 'form-control', 'form': ''}),
        initial=25
    )

ibis_core/themes/forms.py
from django import forms

# place form definition here

ibis_core/users/forms.py
from django import forms
from django.contrib.auth.models import Group as AuthGroup

from ibis_core.users.models import User


class UserCreateForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=AuthGroup.objects.all(),
        label='Permission Group'
    )

    email = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'groups', 'is_subscribed']
        widgets = {
            'first_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'last_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'email': forms.TextInput(attrs={'style': "text-transform: lowercase;"}),
            'password': forms.PasswordInput()
        }

    def save(self, commit=True):
        self.user = super(UserCreateForm, self).save()

        password = self.cleaned_data["password"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class UserEditForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=AuthGroup.objects.all(),
        label='Permission Group'
    )

    def __init__(self, user, *args,**kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        if not user.is_ibis_superadmin:
            del self.fields['groups']

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'groups', 'is_subscribed']
        widgets = {
            'first_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'last_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'email': forms.TextInput(attrs={'style': "text-transform: lowercase;"}),
        }

ibis_core/templates/dashboard.html
{% extends "base.html" %}
{% load static i18n pipeline ibis_tags %}
{% block title %}Dashboard{% endblock %}

{% block css %}
  <!-- Additional styles goes here -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {% stylesheet 'dashboard_css' %}
{% endblock %}

{% block content %}
    <div class="row class-activity-wrapper" id="">
        <div class="col-sm-12 col-md-12">
            <div class="table-responsive">
                <table class="table table-striped" id="activity-table">
                    <thead>
                    <tr>
                        <th >
                            <em class="icon-activity"></em>
                            Activity
                            <span class="glyphicon glyphicon-menu-down"></span>
                            <a href="{% url 'activities_list' %}" class="btn">View All</a>
                        </th>
                        <th class=""><em class="icon-date"></em>Date<span class="glyphicon glyphicon-menu-down"></span></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for activity in user_activities %}
                    <tr>
                        <td>{{ activity }}</td>
                        <td>{{ activity.created|date:"d-M-Y" }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% if request.user.is_authenticated %}
        <div class="row" id="dashboard-user-items">
            <div class="col-sm-4 col-md-4" id="id-your-groups">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWEh5z7jpjAWMp5lPmt30CbIfXoUs1Ks9OOkZSrO_xoZWr7en0" alt="" id="icon-test">

                        <h3 class="panel-title pull-left" style=""><a href="{% url 'groups:list' %}">Your
                            groups</a></h3>

                        <div class="btn-group pull-right">
                            <a href="{% url 'groups:list' %}" class="btn btn-default btn-sm">View Groups</a>
                        </div>

                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <div class="row">
                                    <div class="col-sm-12 col-md-12">
                                        <ul class="list-group">
                                            {% for group in user_groups %}
                                                <li class="list-group-item">
                                                    <a href="{% url "groups:detail" group.slug %}">
                                                        {{ group.name }}
                                                    </a>

                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-sm-4 col-md-4" id="id-your-issues">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWEh5z7jpjAWMp5lPmt30CbIfXoUs1Ks9OOkZSrO_xoZWr7en0" alt="" id="icon-test">

                        <h3 class="panel-title pull-left" style=""><a href="{% url 'issues:list' %}">Your
                            issues</a></h3>

                        <div class="btn-group pull-right">
                            <a href="{% url 'issues:list' %}" class="btn btn-default btn-sm">View Issues</a>
                        </div>

                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            {% for issue in user_issues %}
                                <li class="list-group-item">
                                    <a href="{% url "issues:detail" issue.slug %}">
                                        {{ issue.name }}
                                    </a>

                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 col-md-4" id="id-your-searches">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWEh5z7jpjAWMp5lPmt30CbIfXoUs1Ks9OOkZSrO_xoZWr7en0" alt="" id="icon-test">

                        <h3 class="panel-title pull-left" style=""><a
                                href="{% url 'searches:list' %}">Your searches</a></h3>

                        <div class="btn-group pull-right">
                            <a href="{% url "searches:create" %}" class="btn btn-default btn-sm">Add Search</a>
                        </div>

                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <ul class="list-group">
                                    {% for search in user_searches %}
                                        <li class="list-group-item">
                                            <a href="{% url 'searches:detail' search.id %}">
                                                {{ search }}
                                            </a>
{#                                        <a href="{% url 'searches:detail' search.id %}" class="button">#}
{#                                            View#}
{#                                        </a>#}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>




            <div class="class-activity-wrapper" id="">
                <div class="col-sm-12 col-md-12">
                    <h2 class="my-saved-articles">MY SEARCH ARTICLES</h2>
                </div>
                <div class="col-sm-12 col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped" id="saved-articles-dashboard">
                            <thead>
                            <tr>
                                <th class=""><em class="icon-notes"></em>Title<span class="glyphicon glyphicon-menu-down"></span></th>
                                <th class=" date-created"><em class="icon-date"></em>Publish Date<span class="glyphicon glyphicon-menu-down"></span></th>
                                <th class=""><em class="icon-location"></em>Location<span class="glyphicon glyphicon-menu-down"></span></th>
                                <th class=""><em class="icon-date"></em>Date Discovered<span class="glyphicon glyphicon-menu-down"></span></th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for article in user_articles %}
                                <tr>
                                    <td>
                                        <a href="{% url 'articles:detail' article.id %}">
                                            {{ article.translated_title }}
                                        </a>
                                    </td>
                                    <td class="date-created">
                                        {% if article.post_date_created %}
                                            {{ article.post_date_created|slice:":10"|date_format:"d-M-Y" }}
                                        {% else %}
                                            {{ article.created|date_format:"d-M-Y" }}
                                        {% endif %}
                                    </td>
                                    <td>{% lorem 2 w random %}</td>
                                    <td>{{ article.created|date_format:"d-M-Y" }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock content %}

{% block per_page_js %}
    <!-- Additional js goes here -->
    {% javascript 'dashboard_js' %}
{% endblock %}

ibis_core/templates/maintenance.html
{% extends "base.html" %}

{% block title %}Page Not found{% endblock %}

{% block content %}
<h1>Maintenance Mode</h1>

<p>
    We are sorry. Site under maintenance now. Please try to visit us later.
</p>
{% endblock content %}