config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from ibis_core.activity.views import ActivitiesListView
from ibis_core.common.views import SuggestView, GlobalSearchView, ThemeChidlrensView, ThemeListViewAPI, \
    UserManagementAPI
from ibis_core.dashboard.views import DashboardView
from ibis_core.searches.views import TestGoogleCSEQuery
from ibis_core.themes.views import ThemeListView

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^search/', view=GlobalSearchView.as_view(), name='global_search'),

    # User management
    url(r'^users/', include('ibis_core.users.urls', namespace='users')),

    # Themes management
    url(r'^themes/', include('ibis_core.themes.urls', namespace='themes')),

    # Groups management
    url(r'^groups/', include('ibis_core.groups.urls', namespace='groups')),

    # Issues management
    url(r'^issues/', include('ibis_core.issues.urls', namespace='issues')),

    # Searches management
    url(r'^searches/', include('ibis_core.searches.urls', namespace='searches')),

    # Articles management
    url(r'^articles/', include('ibis_core.articles.urls', namespace='articles')),

    url(r'^feedback/', include('ibis_core.feedback.urls', namespace='feedbacks')),

    # Daily Digest management
    url(r'^digest/', include('ibis_core.digest.urls', namespace='digest')),

    # User accounts management
    url(r'^accounts/', include('allauth.urls')),

    url(r'^activities/', view=ActivitiesListView.as_view(), name='activities_list'),



    url(r'^api/v1/testquery',
        view=TestGoogleCSEQuery.as_view(),
        name='api_testquery'),

    url(r'^api/v1/suggest',
        view=SuggestView.as_view(),
        name='api_suggest'),


    url(r'^api/v1/theme/(?P<slug>[\w-]+)$',
        view=ThemeChidlrensView.as_view(),
        name='api_um_theme'),

    url(r'^api/v1/themes$',
        view=ThemeListViewAPI.as_view(),
        name='api_um_themes'),

    url(r'^api/v1/umdata$',
        view=UserManagementAPI.as_view(),
        name='api_um_data'),





    # Your stuff: custom urls includes go here

    # Summernote WYSIWYG editor URL's
    url(r'^summernote/', include('django_summernote.urls')),

    # Included Django Comments
    url(r'^comments/', include('django_comments_xtd.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

ibis_core/digest/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the DigestListView
    url(
        regex=r'^$',
        view=views.DigestListView.as_view(),
        name='list'
    ),

    # URL pattern for the DigestDetailView
    url(
        regex=r'^(?P<pk>[\w-]+)$',
        view=views.DigestDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the DigestUpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.DigestUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^(?P<pk>[\w-]+)/~approvestate$',
        view=views.DigestApproveStateView.as_view(),
        name='approvestate'
    ),

    # url(
    #     regex=r'^(?P<digest_pk>[0-9a-z-]+)/~remove_article/(?P<article_pk>[0-9a-z-]+)$',
    #     view=views.DigestRemoveArticleView.as_view(),
    #     name='remove-article-from-digest'
    # )
]

ibis_core/groups/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from ibis_core.groups.views import GroupAddExistingIssueView
from . import views
from ibis_core.issues.views import IssueCreateView

urlpatterns = [
    # URL pattern for the GroupListView
    url(
        regex=r'^$',
        view=views.GroupListView.as_view(),
        name='list'
    ),

    # URL pattern for the CreateGroup
    url(
        regex=r'^~new/$',
        view=views.GroupCreateView.as_view(),
        name='create'
    ),

    # URL pattern for the GroupDetailView
    url(
        regex=r'^(?P<slug>[\w-]+)$',
        view=views.GroupDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the GroupUpdateView
    url(
        regex=r'^(?P<slug>[\w-]+)/~update$',
        view=views.GroupUpdateView.as_view(),
        name='update'
    ),

    # Urls for group issues
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_issue/$',
        view=IssueCreateView.as_view(),
        name='add_group_issue'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~add_existing_issue/$',
        view=GroupAddExistingIssueView.as_view(),
        name='add_group_existing_issue'
    ),

    # Urls for user management inside group
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_members/$',
        view=views.GroupUsersAddView.as_view(),
        name='add_group_member_list'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~to_moderator/(?P<pk>[0-9]+)$',
        view=views.GroupUserToModerator.as_view(),
        name='to_moderator'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~remove_member/(?P<pk>[0-9]+)$',
        view=views.GroupUsersDeleteView.as_view(),
        name='remove_group_member'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~follow/$',
        view=views.GroupFollowView.as_view(),
        name='group_follow'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~unfollow/$',
        view=views.GroupUnfollowView.as_view(),
        name='group_unfollow'
    ),

]

ibis_core/issues/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django_comments.feeds import LatestCommentFeed

from ibis_core.issues.views import IssueAddExistingSearchView
from ibis_core.searches.views import SearchCreateView
from . import views

urlpatterns = [
    # URL pattern for the IssueListView
    url(
        regex=r'^$',
        view=views.IssueListView.as_view(),
        name='list'
    ),

    # URL pattern for the CreateIssue
    url(
        regex=r'^~new/$',
        view=views.IssueCreateView.as_view(),
        name='create'
    ),

    # URL pattern for creating issue form selected articles
    url(
        regex=r'^~new-issue-articles/$',
        view=views.IssueCreateFromArticlesView.as_view(),
        name='create-from-articles'
    ),

    # URL pattern for add articles ti existing issue
    url(
        regex=r'^~add-articles/$',
        view=views.IssueUpdateFromSearchView.as_view(),
        name='add-articles'
    ),

    # URL pattern for the IssueDetailView
    url(
        regex=r'^(?P<slug>[\w-]+)$',
        view=views.IssueDetailView.as_view(),
        name='detail'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~update$',
        view=views.IssueUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/access/~update$',
        view=views.IssueAccessibilityView.as_view(),
        name='update_access'
    ),


    # Url for issue search
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_search/$',
        view=SearchCreateView.as_view(),
        name='add_issue_search'
    ),

    # Url for adding existing search/searches
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_existing_search/$',
        view=IssueAddExistingSearchView.as_view(),
        name='add_existing_search'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~follow/$',
        view=views.IssueFollowView.as_view(),
        name='issue_follow'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~unfollow/$',
        view=views.IssueUnfollowView.as_view(),
        name='issue_unfollow'
    ),

    # Include latest comments to issues dashboard
    url(r'^feeds/comments/$', LatestCommentFeed(), name='comments-feed'),

]

ibis_core/searches/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the SearchListView
    url(
        regex=r'^$',
        view=views.SearchListView.as_view(),
        name='list'
    ),

    # URL pattern for the CreateIssue
    url(
        regex=r'^~new/$',
        view=views.SearchCreateView.as_view(),
        name='create'
    ),
    # URL pattern for the SearchDetailView
    url(
        regex=r'^(?P<pk>[\w-]+)$',
        view=views.SearchDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the SearchUpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.SearchUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^(?P<pk>[\w-]+)/~activestate$',
        view=views.SearchChangeActiveStateView.as_view(),
        name='activestate'
    ),

    url(
        regex=r'^filters/',
        view=views.SearchFilteringView.as_view(),
        name='filters'
    ),

    # url(
    #     regex=r'^~save-search/$',
    #     view=views.SaveSearchFiltersView.as_view(),
    #     name='save_search'
    # ),




    # url(
    #     regex=r'^(?P<pk>[\w-]+)/~deactivate$',
    #     view=views.SearchDeactivateView.as_view(),
    #     name='deactivate'
    # ),
]

ibis_core/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    url(
        regex=r'^profile$',
        view=views.UserProfileView.as_view(),
        name='profile'
    ),

    # URL pattern for the UserCreateView
    url(
        regex=r'^~new/$',
        view=views.UserCreateView.as_view(),
        name='create'
    ),


    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.UserEditView.as_view(),
        name='update_user'
    ),

]

ibis_core/searches/models.py
import hashlib

import requests
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

from ibis_core.activity.models import EventMixin
from ibis_core.common.crawler_client import CrawlerClient
from ibis_core.common.models import AbstractBaseModel, AbstractNamedModel
from ibis_core.issues.models import Issue, IssueUsers
from ibis_core.users.models import User
from ibis_core.common.constants import CHANNELS


def get_sources_list():
    try:
        sources_list = CrawlerClient().get_sources_list()
    except:
        sources_list = [
            ['google', 'Google'],
            ['google_cse', 'Google CSE'],
            ['google_blogs', 'Google Blogs'],
            ['google_news', 'Google News'],
            ['google_scholar', 'Google Scholar'],
            # ['bing', 'Bing'],
            # ['yandex', 'Yandex']
        ]

    return sources_list


def get_search_type_list():
    try:
        type_list = CrawlerClient().get_search_types_list()
    except:
        type_list = [
            ['simple_search', 'Simple Search'],
            ['search_engine', 'Advanced Search'],
            ['rss', 'RSS Feed'],
            ['article', 'Article'],
            ['email', 'Email']
        ]

    return type_list


def get_search_query_hash(object):
    to_hash = ''
    h = hashlib.new('ripemd160')
    if object.type == 'search_engine':
        to_hash += object.main_query
    elif object.type == 'rss':
        to_hash += object.rss_link
    elif object.type == 'article':
        to_hash += object.direct_url
    h.update(to_hash.encode())
    return h.hexdigest()


class Search(AbstractBaseModel, EventMixin):
    """
    Represents search instance. Search doesn't need to be associated with an
    Issue, so foreign key can be empty.
    """

    PERIODS = (
        ('hourly', 'Hourly'),
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly')
    )

    class Meta:
        ordering = ['-created']

    issues = models.ManyToManyField(Issue, related_name='searches', blank=True, db_index=True)

    author = models.ForeignKey(User, related_name='searches')

    # Query for searching at search engines - if provided
    main_query = models.TextField(null=True, blank=True)

    # Direct RSS link - if provided
    rss_link = models.CharField(max_length=1000, blank=True, null=True)

    # Direct News/Blog article url - if provided
    direct_url = models.CharField(max_length=1000, blank=True, null=True)

    # Should help to compose bunch of subqueries
    query_template = models.TextField(null=True, blank=True)

    # Stores user generated or automatically generated similar queries
    subqueries = JSONField(blank=True, null=True)

    # If false the system shouldn't serve the search
    active = models.BooleanField(default=True)

    options = JSONField(blank=True, null=True)

    period = models.CharField(max_length=20, choices=PERIODS, default='daily', blank=True)

    source = models.CharField(max_length=200, default='google_cse',
                              help_text='Type please with 1 backspace and 1 coma btw words. Ex.: google, yahoo')

    channel = models.CharField(max_length=64, blank=True, choices=CHANNELS, default='general')

    type = models.CharField(max_length=50, choices=get_search_type_list(), default='')

    name = models.CharField(max_length=1000, unique=True, blank=True)

    def get_update_url(self):
        return reverse('searches:update', args=[str(self.id)])

    def has_edit_rights(self, user):
        """
        Checks whether user has rights to edit the search
        :param user: user
        :return: BOOL
        """
        result = user == self.author
        for issue in self.issues.all():
            result = result or user in issue.member_list()

        return result or user.is_ibis_superadmin

    def __str__(self):
        return '{0} - {1} / [type: {2}]'.format(self.name if self.name else 'Unnamed search', self.period,
                                                self.type)

    @models.permalink
    def get_absolute_url(self):
        return 'searches:detail', (), {'pk': self.id}


class SuggestedSearch(AbstractNamedModel):
    """
    Suggested searches based on user filters and search queries that user saves on searches:filters page
    """
    query = models.TextField(null=True, blank=True)
    initials = models.TextField(blank=True, null=True)
    user = models.ForeignKey('users.User')


@receiver(post_save, sender=Search)
def my_handler(sender, instance, created, **kwargs):

    data = dict(
        search_id=instance.id,
        search_type=instance.type,
        rss_link=instance.rss_link,
        article_url=instance.direct_url,
        query=instance.main_query,
        source=instance.source,
        active=instance.active,
        period=instance.period,
        channel=instance.channel
    )

    try:
        CrawlerClient().create_or_update_search_query(data=data)
    except requests.exceptions.ConnectionError:
        pass

ibis_core/articles/forms.py
import json

from django import forms
from django_summernote.widgets import SummernoteWidget

from ibis_core.articles.models import Article


class ArticleEditForm(forms.ModelForm):
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs={
                               'class': 'form-control'}))

    class Meta:
        model = Article
        fields = ['body', 'translated_body', 'status', 'channel']
        widgets = {
            'body': SummernoteWidget(),
            'translated_body': SummernoteWidget(),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'channel': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_tags(self):
        data = self.data.get('tags')
        cleaned_tags = list(set(data.split(',')))
        return cleaned_tags


class StatusChangeAjaxForm(forms.ModelForm):
    # status = forms.CharField(required=True, widget=forms.Select(attrs={
    #     'class': 'form-control'
    # }))
    class Meta:
        model = Article
        fields = ('status',)
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

ibis_core/digest/forms.py
from django import forms

from ibis_core.digest.models import DailyDigest


class DigestArticleRemoveForm(forms.Form):
    article = forms.CharField(widget=forms.HiddenInput())


class DigestApproveStateForm(forms.Form):
    state = forms.CharField(widget=forms.HiddenInput())

ibis_core/templates/searches/search_detail.html
{% extends "base.html" %}
{% load static django_bootstrap_breadcrumbs search_tags %}

{% block title %}Search: {{ object.main_query }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Searches" "searches:list" %}
  {% breadcrumb object.name "searches:detail" %}
{% endblock %}

{% block content %}
    <div class="row" id="id-search-detail">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <h1>{{ object.main_query }}</h1>
                    {% if can_edit %}
                        <a href="{% url 'searches:update' object.id %}" class="btn btn-success">Edit</a>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8 col-md-8">
                    <dl class="dl-horizontal">
                      <dt>Source</dt>
                      <dd>{% if object.type == 'rss' %} RSS {% else %} {{ object.source }} {% endif %}</dd>
                      <dt>Period</dt>
                      <dd>{{ object.get_period_display }}</dd>
                    </dl>
                </div>
                <div class="col-sm-4 col-md-4">
                    {% search_info object %}
                </div>
            </div>

        </div>
    </div>
    {% if articles|length > 0 %}

    <div class="pagination">
        <span class="step-links">
            {% if articles.has_previous %}
                <a href="?page={{ articles.previous_page_number }}">Prev</a>
            {% endif %}

            <span class="current">
                Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
            </span>

            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}">Next</a>
            {% endif %}
        </span>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-12">
            <ul id="search-results">
                {% for article in articles %}
                <li>
                    <div class="result-title">
                        <a href="{% url "articles:detail" article.id %}">{% if article.translated_title %}
                              {{ article.translated_title }}{% else %}{{ article.title }}{% endif %}</a>
                    </div>
                    <div class="result-url">
                        <span>
                            {{ article.article_url }}
                        </span>
                    </div>
                    <div class="result-text">
                        {% if article.top_image_path %}
                            <img src="{{ article.top_image_path }}" />
                            <div>
                                <div>{{ article.translated_body | truncatewords:100 }}</div>
                            </div>
                        {% else %}
                            {{ article.translated_body | truncatewords:100 }}
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock content %}

ibis_core/templates/searches/search_list.html
{% extends "base.html" %}
{% load static django_bootstrap_breadcrumbs %}{% load i18n %}
{% block title %}Searches{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Searches" "searches:list" %}
{% endblock %}

{% block content %}

<div class="container" id="id-search-list">

   <!-- <h2>Searches</h2>-->
<div class="row">
            <div class="col-sm-12">
                <a href="{% url 'searches:create' %}" class="btn btn-success"><em id="id-figure-plus"></em><span>Add Search</span></a>
            </div>
        </div>
    <div class="row" id="id-searches-list">
        {% for search in search_list %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4>
                        <a href="{% url 'searches:detail' search.id %}">{{ search.name|default:search.main_query|truncatechars:40 }}</a>
                        <br/>
                        <small>{{ search.get_type_display }}</small>
                    </h4>

                    <p><small class="text-muted">Last updated at: {{ search.modified }}</small></p>
                    {% if search.active %}
                      <span >
                        <form style="display: inline-block" action="{% url "searches:activestate" search.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="active" value="0">
                            <button class="btn btn-danger" type="submit">Deactivate</button>
                        </form>
                      </span>
                    {% else %}
                      <span >
                        <form style="display: inline-block" action="{% url "searches:activestate" search.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="active" value="1">
                            <button class="btn btn-primary" type="submit">Activate</button>
                        </form>
                      </span>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'searches:update' search.id %}" >Edit</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

ibis_core/templates/searches/search_results.html
<!-- <ul id="search-results"> -->
<div class="row">
    {% if articles %}
        <div class="col-sm-12">
            <form method="POST" id="issue-create-from-articles">
                {% csrf_token %}
            <!-- <div class="col-md-12"> -->
            {% if articles %}
            <input type="hidden" name="access" value="public">
            <ul id="search-results">
                {% for article in articles %}
                    <li>
                        <div class="result-title">
                            {% if not without_chekboxes %}
                            <input type="checkbox" name="articles" value="{{ article.id }}">
                            {% endif %}
                            <a href="{% url "articles:detail" article.id %}">{% if article.translated_title %}
                              {{ article.translated_title }}{% else %}{{ article.title }}{% endif %}</a>

                        </div>
                        <div class="result-url">
                            {{ article.article_url }}
                        </div>
                        <div class="result-text">
                            {% if article.top_image_path %}
                                <img src="{{ article.top_image_path }}"/>
                                <div>
                                    <div>{{ article.translated_body|truncatewords:100|safe}}</div>
                                </div>
                            {% else %}
                                {{ article.translated_body|truncatewords:100|safe }}
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
                {% if not without_chekboxes %}
                <div style="padding-bottom: 10px;" class="row">
                    <div class="col-md-6">
                        <!-- SUBMITTING GROUP FOR CREATING ISSUE -->
                        <div class="input-group">
                            <input type="text" name="name" placeholder="Issue name" class="form-control"
                                   form="issue-create-from-articles">
                            <div class="input-group-btn">
                                <button type="submit" name="update"
                                        formaction="{% url 'issues:create-from-articles' %}"
                                        value="{{ True }}" class="btn btn-default btn-block">Create Issue
                                </button>
                            </div>
                            <!-- /btn-group -->
                        </div>
                    </div>
                    <div class="col-md-6">
                        <!-- SUBMITTING GROUP FOR UPDATING ISSUE -->
                        <div class="input-group">
                            <select type="" name="pk" class="form-control">
                                <option>Choose an Issue</option>
                                {% for issue in user_issues %}
                                    <option value="{{ issue.pk }}">{{ issue.name }}</option>
                                {% endfor %}
                            </select>
                            <div class="input-group-btn">
                                <button type="submit" name="update"
                                        formaction="{% url 'issues:add-articles' %}"
                                        value="{{ True }}" class="btn btn-default btn-block">Update Issue
                                </button>
                            </div>
                            <!-- /btn-group -->
                        </div>
                        <!-- /input-group -->
                    </div>
                </div>
                {% endif %}
            </ul>
            </form>
            {% endif %}
            <!-- </div> -->
        </div>
    {% endif %}
    <!-- </ul> -->
</div>

ibis_core/templates/searches/searches_select_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Searches{% endblock %}

{% block content %}

<div class="container" id="id-searches-select-list">

    <h2>Select Searches</h2>

    <form method="POST">{% csrf_token %}
        <input type="hidden" name="issue_id" value="{{ issue_id }}">
        <div class="form-group">
            <div class="list-group">
                {% for search in searches_list %}
                  <div class="list-group-item">
                      <input name="_selected_searches" value="{{ search.id }}" type="checkbox">
                      <span class="list-group-item-heading">{{ search.name }}</span>
                  </div>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>

</div>

{% endblock content %}