config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from ibis_core.activity.views import ActivitiesListView
from ibis_core.common.views import SuggestView, GlobalSearchView, ThemeChidlrensView, ThemeListViewAPI, \
    UserManagementAPI
from ibis_core.dashboard.views import DashboardView
from ibis_core.searches.views import TestGoogleCSEQuery
from ibis_core.themes.views import ThemeListView

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^search/', view=GlobalSearchView.as_view(), name='global_search'),

    # User management
    url(r'^users/', include('ibis_core.users.urls', namespace='users')),

    # Themes management
    url(r'^themes/', include('ibis_core.themes.urls', namespace='themes')),

    # Groups management
    url(r'^groups/', include('ibis_core.groups.urls', namespace='groups')),

    # Issues management
    url(r'^issues/', include('ibis_core.issues.urls', namespace='issues')),

    # Searches management
    url(r'^searches/', include('ibis_core.searches.urls', namespace='searches')),

    # Articles management
    url(r'^articles/', include('ibis_core.articles.urls', namespace='articles')),

    url(r'^feedback/', include('ibis_core.feedback.urls', namespace='feedbacks')),

    # Daily Digest management
    url(r'^digest/', include('ibis_core.digest.urls', namespace='digest')),

    # User accounts management
    url(r'^accounts/', include('allauth.urls')),

    url(r'^activities/', view=ActivitiesListView.as_view(), name='activities_list'),



    url(r'^api/v1/testquery',
        view=TestGoogleCSEQuery.as_view(),
        name='api_testquery'),

    url(r'^api/v1/suggest',
        view=SuggestView.as_view(),
        name='api_suggest'),


    url(r'^api/v1/theme/(?P<slug>[\w-]+)$',
        view=ThemeChidlrensView.as_view(),
        name='api_um_theme'),

    url(r'^api/v1/themes$',
        view=ThemeListViewAPI.as_view(),
        name='api_um_themes'),

    url(r'^api/v1/umdata$',
        view=UserManagementAPI.as_view(),
        name='api_um_data'),





    # Your stuff: custom urls includes go here

    # Summernote WYSIWYG editor URL's
    url(r'^summernote/', include('django_summernote.urls')),

    # Included Django Comments
    url(r'^comments/', include('django_comments_xtd.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

ibis_core/digest/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the DigestListView
    url(
        regex=r'^$',
        view=views.DigestListView.as_view(),
        name='list'
    ),

    # URL pattern for the DigestDetailView
    url(
        regex=r'^(?P<pk>[\w-]+)$',
        view=views.DigestDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the DigestUpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.DigestUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^(?P<pk>[\w-]+)/~approvestate$',
        view=views.DigestApproveStateView.as_view(),
        name='approvestate'
    ),

    # url(
    #     regex=r'^(?P<digest_pk>[0-9a-z-]+)/~remove_article/(?P<article_pk>[0-9a-z-]+)$',
    #     view=views.DigestRemoveArticleView.as_view(),
    #     name='remove-article-from-digest'
    # )
]

ibis_core/groups/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from ibis_core.groups.views import GroupAddExistingIssueView
from . import views
from ibis_core.issues.views import IssueCreateView

urlpatterns = [
    # URL pattern for the GroupListView
    url(
        regex=r'^$',
        view=views.GroupListView.as_view(),
        name='list'
    ),

    # URL pattern for the CreateGroup
    url(
        regex=r'^~new/$',
        view=views.GroupCreateView.as_view(),
        name='create'
    ),

    # URL pattern for the GroupDetailView
    url(
        regex=r'^(?P<slug>[\w-]+)$',
        view=views.GroupDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the GroupUpdateView
    url(
        regex=r'^(?P<slug>[\w-]+)/~update$',
        view=views.GroupUpdateView.as_view(),
        name='update'
    ),

    # Urls for group issues
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_issue/$',
        view=IssueCreateView.as_view(),
        name='add_group_issue'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~add_existing_issue/$',
        view=GroupAddExistingIssueView.as_view(),
        name='add_group_existing_issue'
    ),

    # Urls for user management inside group
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_members/$',
        view=views.GroupUsersAddView.as_view(),
        name='add_group_member_list'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~to_moderator/(?P<pk>[0-9]+)$',
        view=views.GroupUserToModerator.as_view(),
        name='to_moderator'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~remove_member/(?P<pk>[0-9]+)$',
        view=views.GroupUsersDeleteView.as_view(),
        name='remove_group_member'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~follow/$',
        view=views.GroupFollowView.as_view(),
        name='group_follow'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~unfollow/$',
        view=views.GroupUnfollowView.as_view(),
        name='group_unfollow'
    ),

]

ibis_core/themes/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from ibis_core.groups.views import GroupCreateView
from . import views

urlpatterns = [
    # URL pattern for the ThemeListView
    url(
        regex=r'^$',
        view=views.ThemeListView.as_view(),
        name='list'
    ),

    # URL pattern for the CreateTheme
    url(
        regex=r'^~new/$',
        view=views.ThemeCreateView.as_view(),
        name='create'
    ),

    # URL pattern for the UpdateTheme
    url(
        regex=r'^(?P<slug>[\w-]+)/~update$',
        view=views.ThemeUpdateView.as_view(),
        name='update'
    ),

    # Urls for user management inside theme
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_members/$',
        view=views.ThemeUsersAddView.as_view(),
        name='add_members'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~to_moderator/(?P<pk>[0-9]+)$',
        view=views.ThemeUserToModerator.as_view(),
        name='to_moderator'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~remove_member/(?P<pk>[0-9]+)$',
        view=views.ThemeUsersDeleteView.as_view(),
        name='remove_theme_member'
    ),

    # Url for creating theme groups
    url(
        regex=r'^(?P<slug>[\w-]+)/~add_group/$',
        view=GroupCreateView.as_view(),
        name='add_theme_group'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/~add_existing_group/$',
        view=views.ThemeAddExistingGroupView.as_view(),
        name='add_theme_existing_group'
    ),

    # URL pattern for the ThemeDetailView
    url(
        regex=r'^(?P<slug>[\w-]+)$',
        view=views.ThemeDetailView.as_view(),
        name='detail'
    ),



]

ibis_core/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    url(
        regex=r'^profile$',
        view=views.UserProfileView.as_view(),
        name='profile'
    ),

    # URL pattern for the UserCreateView
    url(
        regex=r'^~new/$',
        view=views.UserCreateView.as_view(),
        name='create'
    ),


    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UpdateView
    url(
        regex=r'^(?P<pk>[\w-]+)/~update$',
        view=views.UserEditView.as_view(),
        name='update_user'
    ),

]

ibis_core/activity/models.py
import uuid

import redis
from django.contrib.contenttypes import fields
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.conf import settings
from django.template.loader import render_to_string

from ibis_core.common.models import AbstractBaseModel

EVENT_TYPE_CREATE = 'create'

# redis_connection = redis.StrictRedis.from_url(settings.REDIS_ACTIVITY_URL)
redis_connection = redis.StrictRedis(host='0.0.0.0', port='6380', db=1, charset="utf-8", decode_responses=True)


class EventManager(models.Manager):
    def get_user_activity_stream(self, user, offset=0, limit=11):
        events_ids = redis_connection.zrange('activity:stream:user:%d' % user.id, offset, limit, desc=True)
        if len(events_ids):
            return self.filter(id__in=events_ids).order_by('-created')
        return []


class Event(AbstractBaseModel):
    objects = EventManager()

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='activities'
    )

    target_content_type = models.ForeignKey(ContentType, related_name='event_target')
    target_id = models.UUIDField(default=uuid.uuid4, editable=False)
    target = fields.GenericForeignKey('target_content_type', 'target_id')

    event_type = models.CharField(max_length=200, default=EVENT_TYPE_CREATE)

    def __str__(self):
        template_name = "activities/%s_activity.txt" % self.event_type
        try:
            repr = render_to_string(template_name=template_name, context=dict(
                actor=self.actor,
                target_model=self.target._meta.model_name,
                target_url=self.target.get_absolute_url,
                target_name=self.target.name
            ))
        except AttributeError:
            repr = self.actor

        return repr


class EventMixin(object):
    class Meta:
        abstract = True

    def create_event(self, actor, event_type=EVENT_TYPE_CREATE):
        target_content_type = ContentType.objects.get_for_model(self)
        Event.objects.create(
            actor=actor,
            target_id=self.id,
            target_content_type_id=target_content_type.id,
            event_type=event_type
        )

    def get_followers(self):
        raise NotImplementedError

ibis_core/common/models.py
import uuid

from django.core.exceptions import ValidationError
from django.db import models

from autoslug import AutoSlugField


class AbstractBaseModel(models.Model):
    """
    An abstract base class model that provides self updating 'created'
    and 'modified' fields to every model that inherits it.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def are_fields_valid(self):
        try:
            self.full_clean()
        except ValidationError:
            return False
        return True

    class Meta:
        abstract = True


class AbstractNamedModel(AbstractBaseModel):
    """
    An abstract base class model that provides name and slug
    """
    name = models.CharField(max_length=200, db_index=True)
    slug = AutoSlugField(populate_from='name', always_update=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

ibis_core/dashboard/models.py
from django.db import models

# Create your models here.

ibis_core/articles/forms.py
import json

from django import forms
from django_summernote.widgets import SummernoteWidget

from ibis_core.articles.models import Article


class ArticleEditForm(forms.ModelForm):
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs={
                               'class': 'form-control'}))

    class Meta:
        model = Article
        fields = ['body', 'translated_body', 'status', 'channel']
        widgets = {
            'body': SummernoteWidget(),
            'translated_body': SummernoteWidget(),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'channel': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_tags(self):
        data = self.data.get('tags')
        cleaned_tags = list(set(data.split(',')))
        return cleaned_tags


class StatusChangeAjaxForm(forms.ModelForm):
    # status = forms.CharField(required=True, widget=forms.Select(attrs={
    #     'class': 'form-control'
    # }))
    class Meta:
        model = Article
        fields = ('status',)
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

ibis_core/comments/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment


class IssueCommentForm(XtdCommentForm):
    title = forms.CharField(
        max_length=256,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('title'),
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super(IssueCommentForm, self).__init__(*args, **kwargs)
        for field_name, field_obj in self.fields.items():
            field_obj.widget.attrs.update({'class': 'form-control'})

    def get_comment_create_data(self):
        data = super(IssueCommentForm, self).get_comment_create_data()
        data.update({'title': self.cleaned_data['title']})
        return data

ibis_core/digest/forms.py
from django import forms

from ibis_core.digest.models import DailyDigest


class DigestArticleRemoveForm(forms.Form):
    article = forms.CharField(widget=forms.HiddenInput())


class DigestApproveStateForm(forms.Form):
    state = forms.CharField(widget=forms.HiddenInput())

ibis_core/issues/forms.py
from django import forms

from ibis_core.issues.models import Issue


class CreateIssueForm(forms.ModelForm):
    """
    Form for creating an Issue and bind chosen articles to it.
    """
    class Meta:
        model = Issue
        fields = ('name', 'access',)


class PaginateArticlesForm(forms.Form):
    def __init__(self, paginate_choices, *args, **kwargs):
        super(PaginateArticlesForm, self).__init__(*args, **kwargs)
        self.fields['paginate_by'].choices = paginate_choices

    paginate_by = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={'class': 'form-control', 'form': ''}),
        initial=25
    )

ibis_core/themes/forms.py
from django import forms

# place form definition here

ibis_core/users/forms.py
from django import forms
from django.contrib.auth.models import Group as AuthGroup

from ibis_core.users.models import User


class UserCreateForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=AuthGroup.objects.all(),
        label='Permission Group'
    )

    email = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'groups', 'is_subscribed']
        widgets = {
            'first_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'last_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'email': forms.TextInput(attrs={'style': "text-transform: lowercase;"}),
            'password': forms.PasswordInput()
        }

    def save(self, commit=True):
        self.user = super(UserCreateForm, self).save()

        password = self.cleaned_data["password"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class UserEditForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=AuthGroup.objects.all(),
        label='Permission Group'
    )

    def __init__(self, user, *args,**kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        if not user.is_ibis_superadmin:
            del self.fields['groups']

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'groups', 'is_subscribed']
        widgets = {
            'first_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'last_name': forms.TextInput(attrs={'style': "text-transform: capitalize;"}),
            'email': forms.TextInput(attrs={'style': "text-transform: lowercase;"}),
        }

ibis_core/templates/themes/theme_detail.html
{% extends "base.html" %}
{% load static django_bootstrap_breadcrumbs %}

{% block title %}Theme: {{ object.name }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Themes" "themes:list" %}
    {% breadcrumb object.name "themes:detail" %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ object.name }}</h2>
            <p class="text-muted">{{ object.description }}</p>
        </div>
    </div>
    <div class="row" id="id-themes-detail">
        <div class="col-sm-7">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="">Groups</h3>
                  <div class="pull-right">
                    <a href="{% url 'themes:add_theme_group' theme.slug %}" class="btn btn-success btn-sm">Add New Group</a>
                    <a href="{% url 'themes:add_theme_existing_group' theme.slug %}" class="btn btn-success btn-sm">Add Existing Groups</a>
                  </div>
              </div>
              <div class="panel-body">
                  <div class="row">
                      {% for group in groups %}
                          <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                              <div class="caption">
                                <h4><a href="{% url 'groups:detail' group.slug %}">{{ group.name }}</a></h4>
                                <p><small class="text-muted">Last updated at: {{ group.modified }}</small></p>
                                <p>
                                    <a href="#" class="btn btn-primary btn-xs btn-block" role="button">Follow</a>
                                </p>
                              </div>
                            </div>
                          </div>
                      {% endfor %}
                  </div>
              </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="">Issues</h3>
              </div>
              <div class="panel-body">
                  <div class="row">
                      {% for issue in issues %}
                          <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                              <div class="caption">
                                <h4><a href="{% url 'issues:detail' issue.slug %}">{{ issue.name }}</a></h4>
                                <p><small class="text-muted">Last updated at: {{ issue.modified }}</small></p>
                                <p>
                                    <a href="#" class="btn btn-primary btn-xs btn-block" role="button">Follow</a>
                                </p>
                              </div>
                            </div>
                          </div>
                      {% endfor %}
                  </div>
              </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="">Searches</h3>
            </div>
            <div class="panel-body">
                  <div class="row">
                      {% for search in searches %}
                        {% include 'searches/blocks/search_line.html' %}
                      {% endfor %}
                  </div>
              </div>
            </div>

            <!--<div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-4">Title</th>
                            <th class="col-md-1">Date</th>
                            <th class="col-md-1">Search ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for article in articles %}
                        <tr>
                            <td><a href="{% url "articles:detail" article.id %}">{{ article.translated_title }}</a></td>
                            <td>{{ article.post_date_created|slice:":10" }}</td>
                            <td><a href="{% url "searches:detail" article.search_query_id %}">{{ article.search_search_query_id }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>-->
        </div>
        <div class="col-sm-5">
            <div class="panel panel-default">
              <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left">Moderators</h3>
              </div>
              <div class="panel-body">
                <div class="row">
                    {% for moderator in object.moderators %}
                      <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                          <img class="img-circle" src="{% static "images/avatar-blank.jpg" %}" alt="User Avatar">
                          <div class="caption">
                            <p><small class="text-center text-muted">{{ moderator.user }}</small></p>
                            <p>
                                <a href="#" class="btn btn-success btn-xs btn-block" role="button">View</a>
                            </p>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="">Members</h3>
                  <div class="btn-group pull-right">
                    <a href="{% url 'themes:add_members' object.slug %}" class="btn btn-success btn-sm">Add New Member</a>
                  </div>
              </div>
              <div class="panel-body">
                <div class="row">
                    {% for member in object.followers %}
                      <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                          <img class="img-circle" src="{% static "images/avatar-blank.jpg" %}" alt="User Avatar">
                          <div class="caption">
                            <p><small class="text-center text-muted">{{ member.user }}</small></p>
                            <p>
                                <a href="{% url 'users:detail' member.user.username %}" class="btn btn-primary btn-xs btn-block" role="button">View</a>
                                <div class="form-group">
                                    <form method="POST" action="{% url 'themes:to_moderator' object.slug member.id%}">
                                        {% csrf_token %}
                                        <input type="checkbox" name="is_moderator" checked value="True" style="display: none;">
                                        <button type="submit" class="btn btn-success btn-xs btn-block" role="button">To Moderators</button>
                                    </form>
                                </div>
                                <form method="POST" action="{% url 'themes:remove_theme_member' object.slug member.id%}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-xs btn-block" role="button">Remove</button>
                                </form>
                            </p>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
              </div>
            </div>
        </div>
    </div>
<div class="row">
    <div class="col-sm-12 col-md-12">
 <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="">Title</th>
                            <th class=" date-created" >Date</th>
                            <th class="">Search ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for article in articles %}
                        <tr>
                            <td><a href="{% url "articles:detail" article.id %}">{{ article.translated_title }}</a></td>
                            <td class="date-created">
                                {% if article.post_date_created %}
                                    {{ article.post_date_created|slice:":10" }}
                                {% else %}
                                    {{ article.created|date:"Y-m-d" }}
                                {% endif %}
                            </td>
                            <td><a href="{% url "searches:detail" article.search_query_id %}">{{ article.search_search_query_id }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
</div>
</div>
{% endblock content %}

ibis_core/templates/themes/theme_form.html
{% extends "base.html" %}
{% load crispy_forms_tags django_bootstrap_breadcrumbs %}

{% block title %}{% if theme %}Edit theme: {{ theme.name }}{% else %}Create new theme{% endif %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Themes" "themes:list" %}
    {% breadcrumb "Add New Theme" "themes:create" %}
{% endblock %}

{% block content %}
    <!--<h1>{% if theme %}Edit theme: {{ theme.name }}{% else %}New theme{% endif %}</h1>-->
    <form class="form-horizontal" method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Save</button>
          </div>
        </div>
    </form>
{% endblock %}

ibis_core/templates/themes/theme_list.html
{% extends "base.html" %}
{% load static user_groups ibis_tags %}{% load i18n %}{% load django_bootstrap_breadcrumbs %}
{% block title %}Themes{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Themes" "themes:list" %}
{% endblock %}

{% block content %}

    <div class="container" id="id-container-themes">
        {% if request.user.is_ibis_superadmin or request.user.is_superuser %}
        <div class="row">
            <div class="col-sm-12">
                <a href="{% url 'themes:create' %}" class="btn btn-success"><em id="id-figure-plus"></em><span>Add Theme</span></a>
            </div>
        </div>
        {% endif %}
        <div class="row">
            {% for theme in theme_list %}
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail" style="min-height: 220px">
                        <div class="caption">
                            <h4><a href="{% url 'themes:detail' theme.slug %}">{{ theme.name }}</a></h4>
                            <a class="btn btn-success pull-right" href="{% url "themes:update" theme.slug %}">Edit</a>
                            <div>
                                <p>
                                    <small class="text-muted">Last updated at: {{ theme.modified |date_format:"jS F Y" }}</small>
                                </p>
                                {% if theme.description %}
                                    <p class="text-muted">
                                        {{ theme.description | truncatewords_html:30 }}
                                    </p>
                                {% endif %}
                            </div>


                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

ibis_core/templates/themes/theme_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags django_bootstrap_breadcrumbs %}

{% block title %}{% if theme %}Edit theme: {{ theme.name }}{% else %}Create new theme{% endif %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Themes" "themes:list" %}
    {% breadcrumb object.name "themes:detail" object.slug %}
    {% breadcrumb "Update" "themes:update" %}
{% endblock %}

{% block content %}
    <h1>{% if theme %}Edit theme: {{ theme.name }}{% else %}New theme{% endif %}</h1>
    <form class="form-horizontal" method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Save</button>
          </div>
        </div>
    </form>
{% endblock %}